plugins {
    id 'java'
    id 'application'
}
application {
    mainClass = 'org.example.Homework'
}
group = 'org.example'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation'org.slf4j:slf4j-api:2.0.18'
    runtimeOnly'ch.qos.logback:logback-core:1.5.35'
    runtimeOnly'ch.qos.logback:logback-classic:1.5.35'
    // Source: https://mvnrepository.com/artifact/org.flywaydb/flyway-core
    implementation 'org.flywaydb:flyway-core:13.4.0'
    // Source: https://mvnrepository.com/artifact/org.flywaydb/flyway-database-postgresql
    implementation 'org.flywaydb:flyway-database-postgresql:13.4.0'
    implementation 'org.postgresql:postgresql:42.7.13'
    // Source: https://mvnrepository.com/artifact/com.zaxxer/HikariCP
    implementation 'com.zaxxer:HikariCP:7.1.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


test {
    useJUnitPlatform()
}