plugins {
    id 'java'
    id 'application'
}
application {
    mainClass = 'org.example.Homework'
}
group = 'org.example'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation'org.slf4j:slf4j-api:2.0.18'
    runtimeOnly'ch.qos.logback:logback-core:1.5.35'
    runtimeOnly'ch.qos.logback:logback-classic:1.5.35'
    // Source: https://mvnrepository.com/artifact/org.flywaydb/flyway-core
    implementation 'org.flywaydb:flyway-core:13.4.0'
    // Source: https://mvnrepository.com/artifact/org.flywaydb/flyway-database-postgresql
    implementation 'org.flywaydb:flyway-database-postgresql:13.4.0'
    implementation 'org.postgresql:postgresql:42.7.13'
    // Source: https://mvnrepository.com/artifact/com.zaxxer/HikariCP
    implementation 'com.zaxxer:HikariCP:7.1.0'
    // Source: https://mvnrepository.com/artifact/org.codehaus.janino/janino
    implementation 'org.codehaus.janino:janino:3.1.12'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Source: https://mvnrepository.com/artifact/org.assertj/assertj-core
    testImplementation 'org.assertj:assertj-core:3.27.7'
    // Source: https://mvnrepository.com/artifact/com.h2database/h2
    testImplementation 'com.h2database:h2:2.5.250'
    // Source: https://mvnrepository.com/artifact/org.mockito/mockito-core
    testImplementation 'org.mockito:mockito-core:5.23.0'
    // Source: https://mvnrepository.com/artifact/org.mockito/mockito-junit-jupiter
    testImplementation 'org.mockito:mockito-junit-jupiter:5.23.0'
}


test {
        jvmArgs "-javaagent:${classpath.find { it.name.contains('mockito-core') }?.absolutePath}"
    useJUnitPlatform()
}