version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pg-docker
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: demoDB
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr -d demoDB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: