# OFF - All logs are disabled. (Except for those explicitly configured org.example)
# DEBUG - All logs, including libraries, are included. (SLF4J, Logback, Gradle)
# WARN or ERROR - Only warnings and errors (useful for production)
root.level=ERROR